### ISSUE TITLE
link to shadertoy data is broken

### ISSUE THREAD

**Issue by jherico** [jtsiomb/shadertoy-view#1]

**Comment by arminkz** [comment]
same problem here, 
dropbox link is dead, please update. thanks in advance.

**Comment by jtsiomb** [comment]
I just noticed this issue. I re-uploaded the data archive, but it's the same old data archive I had in 2013. Nowadays shadertoy has a lot more sample data, and I think their shader code "template" has also changed, so I'm not sure any of this will work without further updating.
